### ISSUE TITLE
[Design] 동화 페이지

### ISSUE THREAD

**Issue by EunJung516** [DayoookE/dayoook-e-client#6]
## :exclamation: **이슈내용**

동화 관련 페이지 구현

:star: **상세 내용**
---

- 동화 목록 페이지 및 동화 페이지 구현

:white_check_mark: **체크리스트**
---

- [x] 동화 목록 페이지 구현
- [x] 동화 페이지 구현

:mag_right: **레퍼런스**
---

❌

**Comment by ss99x2002** [comment]
종설 화이팅 ~~
